server:
  port: 8084

spring:
  application:
    name: stocks-domain
  data:
    mongodb:
      uri: mongodb+srv://admin:pass1@cluster0.9ixrwlr.mongodb.net/?retryWrites=true&w=majority
      database: stocksCommand
  datasource:
    url: jdbc:mysql://localhost:3306/stocksQuery
    username: root
    password: pass@word1
    application:
      name: stocks-domain
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      group-id: stocksQuery
      properties:
        spring:
          json:
            trusted:
              packages: '*'
            type:
              mapping:
                stocksEvent: com.market.stock.stocksdomain.dto.StocksEvent
      topic: saveStocksCommand
    consumer:
      bootstrap-servers: localhost:9092
      group-id: stocksQuery
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: '*'
            type:
              mapping:
                stocksEvent: com.market.stock.stocksdomain.dto.StocksEvent
      topic: saveStocksCommand

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka